// Cricket Players Data
export const cricketPlayers = [
  { id: 1, name: 'Sangamesh', initialBid: 500, rating: 'Intermediate', type: 'Bowler' },
  { id: 2, name: 'Shafiulla Khan', initialBid: 800, rating: 'Advanced', type: 'Batsman' },
  { id: 3, name: 'Rajendra Devadiga', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 4, name: 'Raju', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 5, name: 'Shivayya', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 6, name: 'Rahul Kumar Shee', initialBid: 800, rating: 'Advanced', type: 'Batsman' },
  { id: 7, name: 'Yenni Hemanth Naidu', initialBid: 500, rating: 'Intermediate', type: 'Bowler' },
  { id: 8, name: 'Rohit Prajapati', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 9, name: 'Gurneet Chhabra', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 10, name: 'Mohammed Arshad', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 11, name: 'Srikanth M G', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 12, name: 'Prateek Kumar Jha', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 13, name: 'Subodh Siddharth', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 14, name: 'Sooriyha SK', initialBid: 500, rating: 'Intermediate', type: 'Batsman' },
  { id: 15, name: 'Navin Kumar Adhithyan', initialBid: 300, rating: 'Beginner', type: 'Batsman' },
  { id: 16, name: 'Abhishek T', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 17, name: 'Anil Kumar Mutte', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 18, name: 'Mohammed Zabiulla', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 19, name: 'Vedant Agrawal', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 20, name: 'Prateek Bhat', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 21, name: 'Kartik Kamble', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 22, name: 'Amit', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 23, name: 'Harish S', initialBid: 800, rating: 'Advanced', type: 'Batsman' },
  { id: 24, name: 'S Yalaguresh', initialBid: 800, rating: 'Advanced', type: 'Batsman' },
  { id: 25, name: 'Saurabh Dewangan', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 26, name: 'Amogh Gokar', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 27, name: 'Shivakumar', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 28, name: 'Shivaraj', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 29, name: 'Aravinda RR', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 30, name: 'Murali Krishna GR', initialBid: 800, rating: 'Advanced', type: 'Batsman' },
  { id: 31, name: 'Suraz Kumar', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 32, name: 'Aftab S', initialBid: 500, rating: 'Intermediate', type: 'Batsman' },
  { id: 33, name: 'Neeraj Plauvadi', initialBid: 500, rating: 'Intermediate', type: 'Batsman' },
  { id: 34, name: 'Botsa Harini', initialBid: 500, rating: 'Intermediate', type: 'Batsman' },
  { id: 35, name: 'Avinash Shanker', initialBid: 500, rating: 'Intermediate', type: 'Batsman' },
  { id: 36, name: 'Ankit Kumar', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 37, name: 'Harshit Bhainsora', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 38, name: 'Syed Khadir', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 39, name: 'Kumar Rhitwik', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 40, name: 'Ranjit', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 41, name: 'Keshav Vyas', initialBid: 500, rating: 'Intermediate', type: 'Bowler' },
  { id: 42, name: 'Ashutosh Tiwari', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 43, name: 'Vikram', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 44, name: 'Yad', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 45, name: 'Subham Sikdar', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 46, name: 'Laraib', initialBid: 300, rating: 'Beginner', type: 'Allrounder' },
  { id: 47, name: 'Mohammed Zabiulla', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 48, name: 'Gyanendra Parmaar', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 49, name: 'Vinod', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 50, name: 'Ranjit Joshy', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 51, name: 'Suraz Kumar', initialBid: 800, rating: 'Advanced', type: 'Allrounder' },
  { id: 52, name: 'Saurabh Dewangan', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 53, name: 'Abhijeet Tiwari', initialBid: 500, rating: 'Intermediate', type: 'Batsman' },
  { id: 54, name: 'Sidharth Saxena', initialBid: 500, rating: 'Intermediate', type: 'Allrounder' },
  { id: 55, name: 'Vardhit Kasliwal', initialBid: 500, rating: 'Intermediate', type: 'Bowler' }
];

// Teams Configuration
export const teams = [
  {
    id: 1,
    name: "Team Abhishek",
    points: 10000,
    color: "#EC1C24",
    players: [],
  },
  {
    id: 2,
    name: "Team Ashutosh",
    points: 10000,
    color: "#F9CD05",
    players: [],
  },
  {
    id: 3,
    name: "Team Srikanth",
    points: 10000,
    color: "#004BA0",
    players: [],
  },
  {
    id: 4,
    name: "Team Kartik ",
    points: 10000,
    color: "#3A225D",
    players: [],
  },
  {
    id: 5,
    name: "Team Rahul",
    points: 10000,
    color: "#004C93",
    players: [],
  },
  {
    id: 6,
    name: "Team Raju",
    points: 10000,
    color: "#254AA5",
    players: [],
  },
];

